# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ResumeCreator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ResumeCreator
  pod 'RealmSwift', '~>10'
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RxSwift'
end
